### ISSUE TITLE
 Compatibility WHMSonic - Shoutcast 2 (MP3 and ACC+)

### ISSUE THREAD

**Issue by msaulohenrique** [RadioHopeUA/Android-HopeFM#2]
Congratulations on the project.

I saw using wowza to stream, would have to adapt to the WHMSonic? Instead of M3U8 for PLS? same or mp3 format.

Thanks for listening!

**Comment by merlin-zaraza** [comment]
Just try to replace `<string name="radio_stream_url" translatable="false">http://stream.hope.ua:1935/hopefm/ngrp:live/playlist.m3u8</string>` with your url from WHMSonic. I'm using ExoPlayer in this project, so it should work.

**Comment by msaulohenrique** [comment]
I changed to http://ninjashost.com.br:9998/listen.pls?sid=1, not work. Because?
If you can you provide a WHMSonic account to test. Just leave your email.

Thank you!

**Comment by merlin-zaraza** [comment]
First, you have to use [ExtractorRendererBuilder](https://github.com/google/ExoPlayer/blob/release-v1/demo/src/main/java/com/google/android/exoplayer/demo/player/ExtractorRendererBuilder.java) instead of HlsRendererBuilder in HopeFMService like:
[https://gist.github.com/merlin-zaraza/1055fb9d259b4fed126cf7ea6992e1df](https://gist.github.com/merlin-zaraza/1055fb9d259b4fed126cf7ea6992e1df)
Then change stream url to: [http://ninjashost.com.br:9998/stream](http://ninjashost.com.br:9998/stream)

**Comment by msaulohenrique** [comment]
I'm using this: https://gist.github.com/msaulohenrique/8d5e0f6382e679ce85a21beb822b9c3c
Working! Thank You 😃 
Repo: https://github.com/msaulohenrique/Android-HopeFM
Comparing changes: https://github.com/RadioHopeUA/Android-HopeFM/compare/master...msaulohenrique:master
